export declare const initHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => HexmapModel;
export declare const updateHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => HexmapModel;
export declare const focusingHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const defocusHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => HexmapModel;
export declare const openHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const addHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const writeHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const readHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const copyHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const geojsonHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const toolHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const saveHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const storeHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const listHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const loadHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
export declare const nameHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => HexmapModel;
export declare const replaceHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => HexmapModel;
export declare const seekHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => HexmapModel;
export declare const selectHexmap: (cpy: HexmapModel, bal: HexmapBit, ste: State) => Promise<HexmapModel>;
import { HexmapModel } from "../hexmap.model";
import HexmapBit from "../fce/hexmap.bit";
import State from "../../99.core/state";
