export declare const INFANT: string;
export declare const TODDLER: string;
export declare const CHILD: string;
export declare const TWEEN: string;
export declare const TEENAGER: string;
export declare const SOLDIER: string;
export declare const JUDGE: string;
export declare const MONARCH: string;
export declare const OLD_AGED: string;
