"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.testShade = exports.patchShade = exports.editShade = exports.runShade = exports.browserShade = exports.bodyShade = exports.openShade = exports.updateShade = exports.initShade = void 0;
var shade_buzz_1 = require("./buz/shade.buzz");
Object.defineProperty(exports, "initShade", { enumerable: true, get: function () { return shade_buzz_1.initShade; } });
var shade_buzz_2 = require("./buz/shade.buzz");
Object.defineProperty(exports, "updateShade", { enumerable: true, get: function () { return shade_buzz_2.updateShade; } });
var shade_buzz_3 = require("./buz/shade.buzz");
Object.defineProperty(exports, "openShade", { enumerable: true, get: function () { return shade_buzz_3.openShade; } });
var shade_buzz_4 = require("./buz/shade.buzz");
Object.defineProperty(exports, "bodyShade", { enumerable: true, get: function () { return shade_buzz_4.bodyShade; } });
var shade_buzz_5 = require("./buz/shade.buzz");
Object.defineProperty(exports, "browserShade", { enumerable: true, get: function () { return shade_buzz_5.browserShade; } });
var shade_buzz_6 = require("./buz/shade.buzz");
Object.defineProperty(exports, "runShade", { enumerable: true, get: function () { return shade_buzz_6.runShade; } });
var shade_buzz_7 = require("./buz/shade.buzz");
Object.defineProperty(exports, "editShade", { enumerable: true, get: function () { return shade_buzz_7.editShade; } });
var shade_buzz_8 = require("./buz/shade.buzz");
Object.defineProperty(exports, "patchShade", { enumerable: true, get: function () { return shade_buzz_8.patchShade; } });
var shade_buzz_9 = require("./buz/shade.buzz");
Object.defineProperty(exports, "testShade", { enumerable: true, get: function () { return shade_buzz_9.testShade; } });
//# sourceMappingURL=shade.buzzer.js.map